<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultNamespace>AlmostCoherent.Testing.ScreenPlayFramework</DefaultNamespace>

    <!-- NuGet metadata -->
    <PackageId>AlmostCoherent.Testing.ScreenPlayFramework</PackageId>
    <Description>This project contains a testing framework for .NET applications. This is based on the more traditional ScreenPlay methodology of testing.</Description>
    <PackageTags>testing;screenplay;</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Playwright\Playwright.csproj" />
	</ItemGroup>

</Project>
