<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultNamespace>AlmostCoherent.Testing.Playwright.Reqnroll</DefaultNamespace>
    <IsTestProject>false</IsTestProject>

    <!-- NuGet metadata -->
    <PackageId>AlmostCoherent.Testing.Playwright.Reqnroll</PackageId>
    <Description>Reqnroll integration for AlmostCoherent.Testing.Playwright. Provides hooks and lifecycle management for Playwright tests using Reqnroll.</Description>
    <PackageTags>testing;playwright;reqnroll;bdd;</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Reqnroll" Version="3.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Playwright\Playwright.csproj" />
	</ItemGroup>

</Project>
